version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: strongpass
      POSTGRES_DB: appdb
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres:
    driver: local
